
FROM maven:3.9.6-eclipse-temurin-11-alpine AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src src

RUN mvn package -DskipTests


FROM openjdk:11

WORKDIR /app

COPY --from=builder /app/target/common-data-service.jar .

EXPOSE 7002

ENTRYPOINT ["java","-jar","common-data-service.jar"]


